### ISSUE TITLE
Decision on sub-module core

### ISSUE THREAD

**Issue by anibalsolon** [radiome-lab/radiome#59]
Hi @puorc 

What is the reasoning behind the move to a new submodule `core` ? It seems redundant.

I understand that as the default workflows will be under a new package/repo, but in the module `radiome.workflows`, it could have some impact. However, it would not bring a problem to installation and packaging to keep as `radiome` (without `core`), unless there is some specific reason I am not aware of.

It would be rather better to keep the core under just `radiome` if there is no impediment, as it keeps development cleaner.

**Comment by puorc** [comment]
As we are planning to distribute our workflows using Python packages, I am considering to add a prefix to all such workflow packages to make it more distinguishable (from other packages). So the workflows are expected to be namespace packages. Their namespace is `radiome`.

Now that `radiome` becomes a namespace(an empty folder in Python) , it can't be a package anymore. Thus, I need to add another package under this namespace, which is radiome.core.

**Comment by anibalsolon** [comment]
I guess `namespace` is just an abstract concept, right? And not a specific construct on Python. I might not be fully aware.

But yes, I see your point. Wouldn't it be more accurate to put them under `radiome.workflows` ? Since this is what they are, and it would prevent them from overwriting the `core` module (i.e. I can create a `core` module on my workflow package). I see in your example (https://github.com/radiome-lab/preprocessing) that they are under `workflows` anyway. In this way, `radiome.workflows` could be the empty module. Python does not have many restrictions on their setup, so if needed, we can provide developers with a `setup.py` that would make whichever package they want to be under `radiome.workflows` (or we can even override their setup.py behavior with what we want).

**Comment by puorc** [comment]
Python 3.3 added implicit namespace packages from [PEP 420](https://www.python.org/dev/peps/pep-0420/). All that is required to create a native namespace package is that you just omit __init__.py from the namespace package directory. An example file structure:
setup.py
mynamespace/
    # No __init__.py here.
------ subpackage_a/
---------- # Sub-packages have __init__.py.
---------- __init__.py
----------  module.py

This is an example from https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages.

I am sorry I just said `radiome` for illustration. Yes all workflows are actually under `radiome.workflows`.  And in my template I provided developers a `setup.py` which would only scan packages under `radiome.workflows`. However, there are other ways to hack namespace packages. We can explore whether there is a better option.

**Comment by anibalsolon** [comment]
Nice about the PEP420, thank you! From my understanding of this PEP and how the workflows are delineated, the namespace per se is indeed `radiome.workflows`, which makes sense since what is "dynamic" here is the workflows (as in this sub-structures are open to change, add more packages, etc). 

Apart from the examples, that treat only cases of the root package being the namespace, there is support for submodules being a namespace. So we just need to specify `packages=find_namespace_packages(include=['radiome.workflows.*'])` and maybe add a .gitkeep in the `radiome/workflow` directory, to keep it in the repo.

**Comment by puorc** [comment]
Yes! That's what we expect.

**Comment by anibalsolon** [comment]
@puorc is this issue solved? On `develop`, it is still under `core`. The point on my comment is that `radiome.workflows` should be an empty folder (i.e. not a module), instead of `radiome`. So `radiome` can still work as a module. Isn't that the case?

**Comment by puorc** [comment]
Hi Anibal, I am so sorry I mistook what you mean. I will try and update the result.

**Comment by puorc** [comment]
Looks like putting all stuff under radiome doesn't work. Once there is a `__init__.py` under `radiome`, it will be treated as a regular package and the namespace will be invalid.

**Comment by anibalsolon** [comment]
That's fine! Lets keep the `core` then.
